"""layout 实际规则正负例，由隔离测试运行。"""

FIXTURES = [
    {"id": "layout-top-level-members-pos", "rule_id": "top-level-members",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"}]},
    {"id": "layout-top-level-members-neg", "rule_id": "top-level-members",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "junk/x.txt", "content": "x"}]},

    {"id": "layout-required-instance-dirs-pos", "rule_id": "required-instance-dirs",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"}]},
    {"id": "layout-required-instance-dirs-neg", "rule_id": "required-instance-dirs",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "remove", "path": "tasks"}]},

    {"id": "layout-on-demand-dirs-common-pos", "rule_id": "on-demand-dirs-common",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "decisions/D-01.md", "content": "# D-01\n"}]},
    {"id": "layout-on-demand-dirs-common-neg", "rule_id": "on-demand-dirs-common",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "decisions", "content": "不是目录\n"}]},

    {"id": "layout-on-demand-dirs-local-pos", "rule_id": "on-demand-dirs-local",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "HANDOFF/STATUS.md", "content": "# 状态\n"}]},
    {"id": "layout-on-demand-dirs-local-neg", "rule_id": "on-demand-dirs-local",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "HANDOFF", "content": "不是目录\n"}]},

    {"id": "layout-root-tracked-closure-pos", "rule_id": "root-tracked-closure",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "git_stage", "paths": ["AGENTS.md", "README.md", ".gitignore"]}]},
    {"id": "layout-root-tracked-closure-neg", "rule_id": "root-tracked-closure",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "stray.txt", "content": "x"},
               {"action": "git_stage", "paths": ["stray.txt"]}]},

    {"id": "layout-sdd-members-pos", "rule_id": "sdd-members",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"}]},
    {"id": "layout-sdd-members-neg", "rule_id": "sdd-members",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "sdd/extra.md", "content": "多余\n"}]},

    {"id": "layout-sdd-architecture-pos", "rule_id": "sdd-members",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "sdd/architecture.md", "content": "# 工程说明\n"}]},
    {"id": "layout-sdd-architecture-case-neg", "rule_id": "sdd-members",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "sdd/Architecture.md", "content": "# 错误大小写\n"}]},
    {"id": "layout-sdd-subdir-neg", "rule_id": "sdd-members",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "sdd/architecture.md/nested.md", "content": "# 不是普通文件\n"}]},
    {"id": "layout-sdd-missing-spec-neg", "rule_id": "sdd-members",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "remove", "path": "sdd/spec.md"},
               {"action": "write_file", "path": "sdd/architecture.md", "content": "# 不能代替规格\n"}]},

    {"id": "layout-unit-dir-grammar-pos", "rule_id": "unit-dir-grammar",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "mechanisms/MECHANISMS.md", "content": "# 花名册\n"},
               {"action": "demo_unit"},
               {"action": "write_file", "path": "mechanisms/demo/hooks/pre-commit", "content": "#!/bin/sh\n"},
               {"action": "write_file", "path": "mechanisms/demo/fixtures/f.txt", "content": "x\n"}]},
    {"id": "layout-unit-dir-grammar-neg", "rule_id": "unit-dir-grammar",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "demo_unit"},
               {"action": "write_file", "path": "mechanisms/stray.md", "content": "x\n"}]},
    {"id": "layout-unit-dir-grammar-subdir-pos", "rule_id": "unit-dir-grammar",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "mechanisms/MECHANISMS.md", "content": "# 花名册\n"},
               {"action": "demo_unit"},
               {"action": "write_file", "path": "mechanisms/demo/adapters/codex.py", "content": "x = 1\n"}]},

    {"id": "layout-design-master-header-pos", "rule_id": "design-master-header",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "demo_unit"}]},
    {"id": "layout-design-master-header-neg", "rule_id": "design-master-header",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file",
                "path": "mechanisms/demo/HarnessPlane_Demo_Design_v1.md",
                "content": "# Demo\n\n> Depends on:\n> 无\n\n缺权威状态行。\n"}]},
    {"id": "layout-design-master-header-neg-dep-path", "rule_id": "design-master-header",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file",
                "path": "mechanisms/demo/HarnessPlane_Demo_Design_v1.md",
                "content": "# Demo\n\n> Depends on:\n> `mechanisms/x.md`\n>\n"
                           "> 权威状态: subject `demo`"
                           "（治理记录目录按所在仓的布局规则解析；唯一状态正本）\n\n正文。\n"}]},
    {"id": "layout-design-master-header-neg-prose-suffix", "rule_id": "design-master-header",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file",
                "path": "mechanisms/demo/HarnessPlane_Demo_Design_v1.md",
                "content": "# Demo\n\n> Depends on:\n> `spec.md` arbitrary prose not IDs\n>\n"
                           "> 权威状态: subject `demo`"
                           "（治理记录目录按所在仓的布局规则解析；唯一状态正本）\n\n正文。\n"}]},
    {"id": "layout-design-master-header-neg-no-blank", "rule_id": "design-master-header",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file",
                "path": "mechanisms/demo/HarnessPlane_Demo_Design_v1.md",
                "content": "# Demo\n> Depends on:\n> 无\n>\n"
                           "> 权威状态: subject `demo`"
                           "（治理记录目录按所在仓的布局规则解析；唯一状态正本）\n\n正文。\n"}]},

    {"id": "layout-task-id-grammar-pos", "rule_id": "task-id-grammar",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"}]},
    {"id": "layout-task-id-grammar-neg", "rule_id": "task-id-grammar",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "tasks/bogus/f.md", "content": "x\n"}]},

    {"id": "layout-evidence-shape-pos", "rule_id": "evidence-shape",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "reviews/demo/r1/judgment.md", "content": "判词\n"},
               {"action": "write_file", "path": "records/governance/demo/decisions.md", "content": "裁定\n"}]},
    {"id": "layout-evidence-shape-neg", "rule_id": "evidence-shape",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "reviews/demo/judgment.md", "content": "判词\n"}]},

    {"id": "layout-staging-not-tracked-pos", "rule_id": "staging-not-tracked",
     "kind": "positive", "expect": "PASS",
     "setup": [{"action": "bootstrap_baseline"}]},
    {"id": "layout-staging-not-tracked-neg", "rule_id": "staging-not-tracked",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": "tasks/gov-t0/attempts/raw.txt", "content": "x\n"},
               {"action": "git_stage", "paths": ["tasks/gov-t0/attempts/raw.txt"]}]},
    {"id": "layout-staging-not-tracked-neg-missing-line", "rule_id": "staging-not-tracked",
     "kind": "negative", "expect": "VIOLATION",
     "setup": [{"action": "bootstrap_baseline"},
               {"action": "write_file", "path": ".gitignore",
                "content": "review-attempts/\n"}]},
]
